package ai.openclaw.app

object AirVisionWindowsProfileHandoffs {
    private const val FAQ_URL = "https://www.asus.com/support/faq/1054069/"
    private const val SUPPORT_URL =
        "https://www.asus.com/displays-desktops/glasses/airvision/asus-airvision-m1/helpdesk_knowledge?model2Name=ASUS-AirVision-M1"

    fun renderMarkdown(
        profileBackup: AirVisionProfileBackup,
        usbState: AirVisionUsbState,
    ): String {
        val activeProfile =
            profileBackup.profiles.firstOrNull { it.viewMode == profileBackup.activeViewMode }
                ?: profileBackup.profiles.firstOrNull()
        val info = usbState.deviceInfo
        val lines =
            buildList {
                add("# AirVision M1 Windows App Profile Handoff")
                add("")
                add(
                    "Generated by OpenClaw HUD for applying Android AirVision profile values in the " +
                        "ASUS AirVision Windows app.",
                )
                add(
                    "Use this when the M1 needs to stay connected to the Fold, or when the Windows/Cyber " +
                        "machine is used later for ASUS-only controls.",
                )
                add("")
                add("## Active Android Profile")
                add("")
                if (activeProfile != null) {
                    addProfile(activeProfile, profileBackup.customLabels, includeHeading = false)
                } else {
                    add("- No AirVision profile values were available.")
                }
                add("")
                add("## Active Android Runtime")
                add("")
                if (activeProfile != null) {
                    addRuntime(activeProfile, profileBackup)
                } else {
                    add("- Runtime profile unavailable because no active profile values were available.")
                }
                add("")
                add("## All Saved Android Profiles")
                add("")
                profileBackup.profiles.sortedBy { AirVisionViewMode.fromRawValue(it.viewMode).ordinal }.forEach { profile ->
                    addProfile(profile, profileBackup.customLabels, includeHeading = true)
                    add("")
                }
                add("## Android HUD Controls")
                add("")
                addControls(profileBackup.hudControls)
                add("")
                add("## Windows-Only Spatial & Mirror Controls")
                add("")
                addWindowsOnlyControls(profileBackup.hudControls)
                add("")
                add("## Android App Preferences")
                add("")
                addPreferences(profileBackup.appPreferences)
                add("")
                add("## Windows/Cyber Apply Checklist")
                add("")
                add("- Open the ASUS AirVision Windows app on Cyber or another Windows host.")
                add(
                    "- Use the active-profile values above as the target View Mode, brightness, distance, " +
                        "IPD, Splendid, Eye Care, Motion Sync, Light Load Mode, and 3D Mode settings.",
                )
                add(
                    "- If Light Load Mode is on, keep IPD and 3D changes locked until Light Load Mode is " +
                        "off, matching the Android HUD guard.",
                )
                add(
                    "- Use Android HUD scale, placement, safe area, and physical-main-screen values only " +
                        "for OpenClaw HUD layout; they are not ASUS firmware settings.",
                )
                add(
                    "- Review the Windows-only spatial and mirror section before expecting Cursor Follow, " +
                        "Center Cursor, 3DoF, or Unity mirror behavior on Android.",
                )
                add(
                    "- After changing ASUS Windows app settings, reconnect the M1 to Android and export " +
                        "diagnostics or profile backup again.",
                )
                add("")
                add("## Android-Visible USB Context")
                add("")
                add("- Connected: ${yesNo(usbState.connected)}")
                add("- USB permission granted: ${yesNo(usbState.permissionGranted)}")
                add("- Device: ${displayValue(usbState.deviceLabel, "not detected")}")
                add("- USB ID: ${displayValue(usbState.vendorProduct ?: info.vendorProduct, "not detected")}")
                add("- Manufacturer: ${displayValue(info.manufacturerName, "not captured")}")
                add("- Product: ${displayValue(info.productName, "not captured")}")
                add("- Interface count: ${info.interfaceCount?.toString() ?: "not captured"}")
                add("- Serial status: ${serialStatus(info)}")
                add(
                    "- Android-visible firmware/version context: " +
                        displayValue(info.firmwareVersion, "pending ASUS HID protocol"),
                )
                add("- Firmware report paths: ${usbState.firmwareCapabilities.summary}")
                add("")
                add("## Android Boundary")
                add("")
                add(
                    "- Android stores these profile values and applies HUD-only effects such as software " +
                        "brightness, virtual distance scaling, HUD scale, placement, and Eye Care overlay.",
                )
                add("- Android does not send ASUS vendor reports until the HID protocol is captured, validated, and live-tested.")
                add(
                    "- Firmware updates, true panel preset writes, Windows mirror windows, virtual cursor, " +
                        "and 3DoF controls remain ASUS Windows app workflows.",
                )
                add(
                    "- This handoff intentionally omits raw USB serial numbers, raw USB captures, auth tokens, " +
                        "gateway endpoints, and chat history.",
                )
                add("")
                add("## ASUS Links")
                add("")
                add("- FAQ and tutorials: $FAQ_URL")
                add("- AirVision M1 support: $SUPPORT_URL")
            }
        return lines.joinToString("\n") + "\n"
    }

    private fun MutableList<String>.addProfile(
        profile: AirVisionBackupDisplayProfile,
        labels: AirVisionBackupCustomLabels,
        includeHeading: Boolean,
    ) {
        val mode = AirVisionViewMode.fromRawValue(profile.viewMode)
        val displayLabel = profileDisplayLabel(mode, labels)
        if (includeHeading) add("### $displayLabel")
        add("- View Mode: ${mode.label}")
        add("- Brightness: ${profile.brightnessPercent}%")
        add("- Screen distance: ${profile.distanceCm} cm")
        add("- IPD: ${ipdValue(profile)}")
        add("- Splendid: ${AirVisionSplendidMode.fromRawValue(profile.splendidMode).label}")
        add("- Blue Light Filter: ${blueLightFilterValue(profile)}")
        add("- Motion Sync: ${onOff(profile.motionSyncEnabled)}")
        add("- Light Load Mode: ${onOff(profile.lightLoadModeEnabled)}")
        add("- 3D Mode: ${threeDValue(profile)}")
        add("- Android HUD scale: ${profile.hudScalePercent}%")
        add("- Android HUD placement: ${AirVisionHudPlacement.fromRawValue(profile.hudPlacement).label}")
        add("- Android safe area: ${profile.safeAreaPercent}%")
        add("- Android physical main screen visible: ${yesNo(profile.physicalMainScreenVisible)}")
        addRuntimeSummary(profile)
    }

    private fun MutableList<String>.addRuntime(
        profile: AirVisionBackupDisplayProfile,
        profileBackup: AirVisionProfileBackup,
    ) {
        val runtime = runtimeProfileForProfile(profile)
        val importedRuntime =
            profileBackup.runtimeProfiles.firstOrNull {
                it.viewMode.trim().lowercase() == profile.viewMode.trim().lowercase()
            }
        add("- Effective HUD scale: ${runtime.effectiveHudScalePercent}%")
        add("- Transcript entries: ${runtime.hudTranscriptEntryCount}")
        add("- Caption entries: ${runtime.hudCaptionEntryCount}")
        add("- IPD adjustment available: ${yesNo(runtime.ipdAdjustmentEnabled)}")
        add("- 3D Mode available: ${yesNo(runtime.threeDModeAvailable)}")
        add("- Eye Care filter available: ${yesNo(runtime.blueLightFilterAvailable)}")
        add("- Color preview overlays: ${onOff(runtime.colorPreviewOverlaysEnabled)}")
        add("- Brightness dimming: ${onOff(runtime.brightnessDimmingEnabled)}")
        add(
            "- Embedded runtime metadata: " +
                when {
                    profileBackup.runtimeProfiles.isEmpty() -> "missing; recalculated from active profile values"
                    importedRuntime == null -> "missing for active profile; recalculated from active profile values"
                    runtimeMatches(importedRuntime, runtime) -> "current"
                    else -> "stale; recalculated from active profile values"
                },
        )
    }

    private fun MutableList<String>.addRuntimeSummary(profile: AirVisionBackupDisplayProfile) {
        val runtime = runtimeProfileForProfile(profile)
        add(
            "- Android runtime summary: effective HUD scale ${runtime.effectiveHudScalePercent}%, " +
                "transcript ${runtime.hudTranscriptEntryCount}, captions ${runtime.hudCaptionEntryCount}, " +
                "overlays ${onOff(runtime.colorPreviewOverlaysEnabled)}, dimming ${onOff(runtime.brightnessDimmingEnabled)}",
        )
        add(
            "- Android runtime controls: IPD ${availableUnavailable(runtime.ipdAdjustmentEnabled)}, " +
                "3D ${availableUnavailable(runtime.threeDModeAvailable)}, " +
                "Eye Care ${availableUnavailable(runtime.blueLightFilterAvailable)}",
        )
    }

    private fun MutableList<String>.addControls(controls: AirVisionBackupHudControls) {
        add("- Single tap: ${AirVisionHudTouchAction.fromRawValue(controls.singleTapAction).label}")
        add("- Double tap: ${AirVisionHudDoubleTapAction.fromRawValue(controls.doubleTapAction).label}")
        add("- Swipe: ${AirVisionHudSwipeAction.fromRawValue(controls.swipeAction).label}")
        add("- Brightness key: ${AirVisionHudKeyAction.fromRawValue(controls.brightnessKeyAction).label}")
        add("- Media key: ${AirVisionHudMediaKeyAction.fromRawValue(controls.mediaKeyAction).label}")
    }

    private fun MutableList<String>.addWindowsOnlyControls(controls: AirVisionBackupHudControls) {
        val brightnessKeyAction = AirVisionHudKeyAction.fromRawValue(controls.brightnessKeyAction)
        add("- Cursor Follow: Windows AirVision app only")
        add("- Center Cursor: Windows AirVision app only")
        add("- 3DoF: Windows laptop/AirVision app only")
        add("- Unity mirror window / Ctrl+Alt+E: Windows AirVision app only")
        add(
            "- Android distance hotkey fallback: " +
                if (brightnessKeyAction == AirVisionHudKeyAction.AdjustDistance) "mapped to M1 brightness keys" else "off",
        )
        add(
            "- Android mirror fallback: use Android Cast, Android Display settings, or Samsung DeX screen sharing outside the HUD",
        )
        add(
            "- M1 touch hardware passthrough: firmware may keep brightness/media behavior before Android receives gesture events",
        )
    }

    private fun MutableList<String>.addPreferences(preferences: AirVisionBackupAppPreferences) {
        val sourceLanguage =
            TranslationCaptionMode.languageFor(
                TranslationCaptionMode.normalizeLanguageCode(
                    preferences.translationCaptionSourceLanguage,
                    TranslationCaptionMode.DEFAULT_SOURCE_LANGUAGE,
                ),
            )
        val targetLanguage =
            TranslationCaptionMode.languageFor(
                TranslationCaptionMode.normalizeLanguageCode(
                    preferences.translationCaptionTargetLanguage,
                    TranslationCaptionMode.DEFAULT_TARGET_LANGUAGE,
                ),
            )
        add("- Startup view: ${AirVisionStartupDestination.fromRawValue(preferences.startupDestination).label}")
        add("- HUD display target: ${AirVisionHudDisplayTarget.fromRawValue(preferences.hudDisplayTarget).label}")
        add("- Companion language: ${AirVisionAppLanguage.fromRawValue(preferences.language).label}")
        add("- Speaker output: ${onOff(preferences.speakerEnabled)}")
        add("- Samsung/native captions: ${onOff(preferences.nativeCaptionsEnabled)}")
        add("- Translation captions: ${sourceLanguage.label} -> ${targetLanguage.label}")
        add("- Demo Mode: ${onOff(preferences.demoModeEnabled)}")
    }

    private fun profileDisplayLabel(
        mode: AirVisionViewMode,
        labels: AirVisionBackupCustomLabels,
    ): String =
        when (mode) {
            AirVisionViewMode.Custom1 -> labels.custom1
            AirVisionViewMode.Custom2 -> labels.custom2
            else -> mode.label
        }

    private fun runtimeProfileForProfile(profile: AirVisionBackupDisplayProfile): AirVisionBackupRuntimeProfile =
        AirVisionProfileBackups.runtimeProfileFromSettings(AirVisionProfileBackups.settingsFromProfile(profile))

    private fun runtimeMatches(
        imported: AirVisionBackupRuntimeProfile,
        derived: AirVisionBackupRuntimeProfile,
    ): Boolean =
        imported.viewMode == derived.viewMode &&
            imported.ipdAdjustmentEnabled == derived.ipdAdjustmentEnabled &&
            imported.threeDModeAvailable == derived.threeDModeAvailable &&
            imported.blueLightFilterAvailable == derived.blueLightFilterAvailable &&
            imported.hudTranscriptEntryCount == derived.hudTranscriptEntryCount &&
            imported.hudCaptionEntryCount == derived.hudCaptionEntryCount &&
            imported.effectiveHudScalePercent == derived.effectiveHudScalePercent &&
            imported.colorPreviewOverlaysEnabled == derived.colorPreviewOverlaysEnabled &&
            imported.brightnessDimmingEnabled == derived.brightnessDimmingEnabled

    private fun blueLightFilterValue(profile: AirVisionBackupDisplayProfile): String =
        if (AirVisionSplendidMode.fromRawValue(profile.splendidMode) == AirVisionSplendidMode.EyeCare) {
            "${profile.blueLightFilterPercent}%"
        } else {
            "off (requires Eye Care)"
        }

    private fun ipdValue(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "${profile.ipdMm} mm (locked by Light Load Mode)"
        } else {
            "${profile.ipdMm} mm"
        }

    private fun threeDValue(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "off (locked by Light Load Mode)"
        } else {
            onOff(profile.threeDModeEnabled)
        }

    private fun displayValue(
        value: String?,
        fallback: String,
    ): String = value?.takeIf { it.isNotBlank() } ?: fallback

    private fun serialStatus(info: AirVisionUsbDeviceInfo): String =
        info.serialStatus?.takeIf { it.isNotBlank() }
            ?: info.serialNumber?.takeIf { it.isNotBlank() }?.let { "available" }
            ?: "not captured"

    private fun onOff(value: Boolean): String = if (value) "on" else "off"

    private fun yesNo(value: Boolean): String = if (value) "yes" else "no"

    private fun availableUnavailable(value: Boolean): String = if (value) "available" else "unavailable"
}
