package ai.openclaw.app

object AirVisionFirmwareUpdateHandoffs {
    private const val FAQ_URL = "https://www.asus.com/support/faq/1054069/"
    private const val SUPPORT_URL =
        "https://www.asus.com/displays-desktops/glasses/airvision/asus-airvision-m1/helpdesk_knowledge?model2Name=ASUS-AirVision-M1"

    fun renderMarkdown(
        usbState: AirVisionUsbState,
        captureResults: AirVisionFirmwareCaptureResults? = null,
    ): String {
        val info = usbState.deviceInfo
        val lines =
            buildList {
                add("# AirVision M1 Firmware Update Handoff")
                add("")
                add(
                    "Generated by OpenClaw HUD for a Windows/Cyber ASUS AirVision app firmware-update session.",
                )
                add("Android keeps firmware writes read-only until the ASUS HID protocol is validated.")
                add("")
                add("## Android-Visible Device Context")
                add("")
                add("- Connected: ${yesNo(usbState.connected)}")
                add("- USB permission granted: ${yesNo(usbState.permissionGranted)}")
                add("- Device: ${displayValue(usbState.deviceLabel, "not detected")}")
                add("- USB ID: ${displayValue(usbState.vendorProduct ?: info.vendorProduct, "not detected")}")
                add("- Manufacturer: ${displayValue(info.manufacturerName, "not captured")}")
                add("- Product: ${displayValue(info.productName, "not captured")}")
                add("- Android device path: ${displayValue(info.deviceName, "not captured")}")
                add("- Interface count: ${info.interfaceCount?.toString() ?: "not captured"}")
                add("- Serial status: ${serialStatus(info)}")
                add("- Android-visible firmware/version context: ${firmwareVersion(info)}")
                add("- Status: ${usbState.statusText}")
                add("")
                add("## Android Interface Readiness")
                add("")
                add("- HID control interface: ${yesNo(usbState.hidControlInterface)}")
                add("- Audio interface: ${yesNo(usbState.audioInterface)}")
                add("- Input interface: ${yesNo(usbState.inputInterface)}")
                add("- Firmware report paths: ${usbState.firmwareCapabilities.summary}")
                add("- Feature readiness: ${usbState.firmwareCapabilities.featureReadinessSummary}")
                add("")
                add("## Imported Protocol-Capture Evidence")
                add("")
                addCaptureResults(captureResults)
                add("")
                add("## Windows/Cyber Update Checklist")
                add("")
                add("- Connect the AirVision M1 directly to the Windows/Cyber machine running the ASUS AirVision app.")
                add("- Use the ASUS AirVision Windows app to check for and install firmware updates.")
                add("- Keep the Android HUD read-only during the update; do not send vendor firmware reports from Android.")
                add("- After the update, reconnect the M1 to Android and export AirVision diagnostics again.")
                add("- Compare the pre/post Android-visible USB descriptor, interface, and version context.")
                add("- If protocol capture is needed, export the firmware capture plan and record sanitized Windows USB evidence.")
                add("")
                add("## ASUS Support Links")
                add("")
                add("- FAQ and tutorials: $FAQ_URL")
                add("- AirVision M1 support: $SUPPORT_URL")
                add("")
                add("## Privacy Notes")
                add("")
                add("- This handoff intentionally omits raw USB serial numbers.")
                add("- Do not commit raw USB captures, private payload bytes, or temporary review/demo credentials.")
            }
        return lines.joinToString("\n") + "\n"
    }

    private fun MutableList<String>.addCaptureResults(captureResults: AirVisionFirmwareCaptureResults?) {
        if (captureResults == null) {
            add("- Imported capture results: none")
            add("- Android firmware writes remain blocked until sanitized capture results are imported and validated.")
            return
        }

        val summary = AirVisionFirmwareCaptureResultFiles.summarize(captureResults)
        val writeEnabledLabels =
            captureResults.features
                .filter { it.androidEnablementDecision == "enable_android_write" }
                .joinToString { it.label }
                .ifBlank { "none" }
        val blockedLabels =
            captureResults.features
                .filter { it.androidEnablementDecision == "blocked" }
                .joinToString { it.label }
                .ifBlank { "none" }
        add("- Imported capture results: ${summary.displayText}")
        add("- Schema/version: ${captureResults.schema} v${captureResults.version}")
        add("- Payload policy: ${displayValue(captureResults.payloadPolicy, "sanitized summaries only")}")
        add("- Feature coverage: ${summary.featureCount} AirVision firmware features")
        add("- Validated features: ${summary.validatedFeatureCount}")
        add("- Android write-enabled features: $writeEnabledLabels")
        add("- Blocked features: $blockedLabels")
        add("- Source notes: ${displayValue(captureResults.source.notes, "not recorded")}")
        add("- Raw USB captures, raw serial values, and payload bytes are intentionally excluded.")
    }

    private fun displayValue(
        value: String?,
        fallback: String,
    ): String = value?.takeIf { it.isNotBlank() } ?: fallback

    private fun firmwareVersion(info: AirVisionUsbDeviceInfo): String =
        info.firmwareVersion?.takeIf { it.isNotBlank() } ?: "pending ASUS HID protocol"

    private fun serialStatus(info: AirVisionUsbDeviceInfo): String =
        info.serialStatus?.takeIf { it.isNotBlank() }
            ?: info.serialNumber?.takeIf { it.isNotBlank() }?.let { "available" }
            ?: "not captured"

    private fun yesNo(value: Boolean): String = if (value) "yes" else "no"
}
