package ai.openclaw.app

object AirVisionWindowsProfileHandoffs {
    private const val FAQ_URL = "https://www.asus.com/support/faq/1054069/"
    private const val SUPPORT_URL =
        "https://www.asus.com/displays-desktops/glasses/airvision/asus-airvision-m1/helpdesk_knowledge?model2Name=ASUS-AirVision-M1"

    fun renderMarkdown(
        profileBackup: AirVisionProfileBackup,
        usbState: AirVisionUsbState,
    ): String {
        val activeProfile =
            profileBackup.profiles.firstOrNull { it.viewMode == profileBackup.activeViewMode }
                ?: profileBackup.profiles.firstOrNull()
        val info = usbState.deviceInfo
        val lines =
            buildList {
                add("# AirVision M1 Windows App Profile Handoff")
                add("")
                add(
                    "Generated by OpenClaw HUD for applying Android AirVision profile values in the " +
                        "ASUS AirVision Windows app.",
                )
                add(
                    "Use this when the M1 needs to stay connected to the Fold, or when the Windows/Cyber " +
                        "machine is used later for ASUS-only controls.",
                )
                add("")
                add("## Active Android Profile")
                add("")
                if (activeProfile != null) {
                    addProfile(activeProfile, profileBackup.customLabels, includeHeading = false)
                } else {
                    add("- No AirVision profile values were available.")
                }
                add("")
                add("## All Saved Android Profiles")
                add("")
                profileBackup.profiles.sortedBy { AirVisionViewMode.fromRawValue(it.viewMode).ordinal }.forEach { profile ->
                    addProfile(profile, profileBackup.customLabels, includeHeading = true)
                    add("")
                }
                add("## Windows/Cyber Apply Checklist")
                add("")
                add("- Open the ASUS AirVision Windows app on Cyber or another Windows host.")
                add(
                    "- Use the active-profile values above as the target View Mode, brightness, distance, " +
                        "IPD, Splendid, Eye Care, Motion Sync, Light Load Mode, and 3D Mode settings.",
                )
                add(
                    "- If Light Load Mode is on, keep IPD and 3D changes locked until Light Load Mode is " +
                        "off, matching the Android HUD guard.",
                )
                add(
                    "- Use Android HUD scale, placement, safe area, and physical-main-screen values only " +
                        "for OpenClaw HUD layout; they are not ASUS firmware settings.",
                )
                add(
                    "- After changing ASUS Windows app settings, reconnect the M1 to Android and export " +
                        "diagnostics or profile backup again.",
                )
                add("")
                add("## Android-Visible USB Context")
                add("")
                add("- Connected: ${yesNo(usbState.connected)}")
                add("- USB permission granted: ${yesNo(usbState.permissionGranted)}")
                add("- Device: ${displayValue(usbState.deviceLabel, "not detected")}")
                add("- USB ID: ${displayValue(usbState.vendorProduct ?: info.vendorProduct, "not detected")}")
                add("- Manufacturer: ${displayValue(info.manufacturerName, "not captured")}")
                add("- Product: ${displayValue(info.productName, "not captured")}")
                add("- Interface count: ${info.interfaceCount?.toString() ?: "not captured"}")
                add("- Serial status: ${serialStatus(info)}")
                add(
                    "- Android-visible firmware/version context: " +
                        displayValue(info.firmwareVersion, "pending ASUS HID protocol"),
                )
                add("- Firmware report paths: ${usbState.firmwareCapabilities.summary}")
                add("")
                add("## Android Boundary")
                add("")
                add(
                    "- Android stores these profile values and applies HUD-only effects such as software " +
                        "brightness, virtual distance scaling, HUD scale, placement, and Eye Care overlay.",
                )
                add("- Android does not send ASUS vendor reports until the HID protocol is captured, validated, and live-tested.")
                add(
                    "- Firmware updates, true panel preset writes, Windows mirror windows, virtual cursor, " +
                        "and 3DoF controls remain ASUS Windows app workflows.",
                )
                add(
                    "- This handoff intentionally omits raw USB serial numbers, raw USB captures, auth tokens, " +
                        "gateway endpoints, and chat history.",
                )
                add("")
                add("## ASUS Links")
                add("")
                add("- FAQ and tutorials: $FAQ_URL")
                add("- AirVision M1 support: $SUPPORT_URL")
            }
        return lines.joinToString("\n") + "\n"
    }

    private fun MutableList<String>.addProfile(
        profile: AirVisionBackupDisplayProfile,
        labels: AirVisionBackupCustomLabels,
        includeHeading: Boolean,
    ) {
        val mode = AirVisionViewMode.fromRawValue(profile.viewMode)
        val displayLabel = profileDisplayLabel(mode, labels)
        if (includeHeading) add("### $displayLabel")
        add("- View Mode: ${mode.label}")
        add("- Brightness: ${profile.brightnessPercent}%")
        add("- Screen distance: ${profile.distanceCm} cm")
        add("- IPD: ${ipdValue(profile)}")
        add("- Splendid: ${AirVisionSplendidMode.fromRawValue(profile.splendidMode).label}")
        add("- Blue Light Filter: ${blueLightFilterValue(profile)}")
        add("- Motion Sync: ${onOff(profile.motionSyncEnabled)}")
        add("- Light Load Mode: ${onOff(profile.lightLoadModeEnabled)}")
        add("- 3D Mode: ${threeDValue(profile)}")
        add("- Android HUD scale: ${profile.hudScalePercent}%")
        add("- Android HUD placement: ${AirVisionHudPlacement.fromRawValue(profile.hudPlacement).label}")
        add("- Android safe area: ${profile.safeAreaPercent}%")
        add("- Android physical main screen visible: ${yesNo(profile.physicalMainScreenVisible)}")
    }

    private fun profileDisplayLabel(
        mode: AirVisionViewMode,
        labels: AirVisionBackupCustomLabels,
    ): String =
        when (mode) {
            AirVisionViewMode.Custom1 -> labels.custom1
            AirVisionViewMode.Custom2 -> labels.custom2
            else -> mode.label
        }

    private fun blueLightFilterValue(profile: AirVisionBackupDisplayProfile): String =
        if (AirVisionSplendidMode.fromRawValue(profile.splendidMode) == AirVisionSplendidMode.EyeCare) {
            "${profile.blueLightFilterPercent}%"
        } else {
            "off (requires Eye Care)"
        }

    private fun ipdValue(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "${profile.ipdMm} mm (locked by Light Load Mode)"
        } else {
            "${profile.ipdMm} mm"
        }

    private fun threeDValue(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "off (locked by Light Load Mode)"
        } else {
            onOff(profile.threeDModeEnabled)
        }

    private fun displayValue(
        value: String?,
        fallback: String,
    ): String = value?.takeIf { it.isNotBlank() } ?: fallback

    private fun serialStatus(info: AirVisionUsbDeviceInfo): String =
        info.serialStatus?.takeIf { it.isNotBlank() }
            ?: info.serialNumber?.takeIf { it.isNotBlank() }?.let { "available" }
            ?: "not captured"

    private fun onOff(value: Boolean): String = if (value) "on" else "off"

    private fun yesNo(value: Boolean): String = if (value) "yes" else "no"
}
