package ai.openclaw.app

object AirVisionFirmwareCapturePlans {
    fun renderMarkdown(
        usbState: AirVisionUsbState,
        displaySettings: AirVisionDisplaySettings = AirVisionDisplaySettings(),
    ): String {
        val capabilities = usbState.firmwareCapabilities
        val targets = capabilities.captureTargets.associateBy { it.feature }
        val syncPlan = AirVisionFirmwareSyncPlans.fromSettings(displaySettings, capabilities)
        val syncItems = syncPlan.items.associateBy { it.feature }
        val lines =
            buildList {
                add("# AirVision M1 Firmware Protocol Capture Plan")
                add("")
                add("Generated by OpenClaw HUD from the Android AirVision firmware feature list.")
                add("")
                add("## Current Android Firmware Link")
                add("")
                add("- Connected: ${yesNo(usbState.connected)}")
                add("- USB permission granted: ${yesNo(usbState.permissionGranted)}")
                add("- Device: ${usbState.deviceLabel?.takeIf { it.isNotBlank() } ?: "not detected"}")
                add("- USB ID: ${usbState.vendorProduct?.takeIf { it.isNotBlank() } ?: "not detected"}")
                add("- Status: ${usbState.statusText}")
                add("- HID control interface: ${yesNo(usbState.hidControlInterface)}")
                add("- Audio interface: ${yesNo(usbState.audioInterface)}")
                add("- Input interface: ${yesNo(usbState.inputInterface)}")
                add("- Firmware report paths: ${capabilities.summary}")
                add(
                    "- Capture readiness: ${
                        if (capabilities.hasWritableHidReports) {
                            "writable HID report path detected"
                        } else {
                            "waiting for writable HID report path"
                        }
                    }",
                )
                add("")
                add("## Desired Firmware Sync")
                add("")
                add(syncPlan.summary)
                add("")
                add("| Feature | Desired value | Android effect | Hardware sync | Blocked reason |")
                add("| --- | --- | --- | --- | --- |")
                AirVisionFirmwareFeature.entries.forEach { feature ->
                    val item = syncItems.getValue(feature)
                    add(
                        "| ${feature.label.escapeTableCell()} | ${item.desiredValue.escapeTableCell()} | " +
                            "${item.androidEffect.escapeTableCell()} | ${item.hardwareSyncStatus.escapeTableCell()} | " +
                            "${item.blockedReason.escapeTableCell()} |",
                    )
                }
                add("")
                add("## Capture Setup")
                add("")
                add(
                    "- Keep the AirVision M1 connected to the Windows/Cyber machine running the ASUS AirVision app " +
                        "when capturing vendor traffic.",
                )
                add("- Capture USB traffic while changing one AirVision setting at a time through the probe values below.")
                add(
                    "- Export Android HUD diagnostics before and after the capture session, then compare readable/writable " +
                        "HID report paths against USBPcap endpoints.",
                )
                add(
                    "- Keep Android firmware writes disabled until the vendor report payload, report ID, length, and " +
                        "checksum behavior are validated from captures.",
                )
                add("- Do not commit raw USB serial numbers, raw private capture payloads, or temporary review/demo credentials.")
                add("")
                add("## Capture Acceptance Criteria")
                add("")
                add(
                    "- Record the exact Windows write report ID, payload bytes, payload length, and endpoint for each " +
                        "feature before Android sends any vendor report.",
                )
                add("- Record any matching readback report ID, payload bytes, endpoint, and timing after each Windows setting change.")
                add("- Identify checksum, framing, sequence, or padding behavior from at least two distinct probe values for the same feature.")
                add("- Confirm the ASUS app UI and the M1 visible state changed as expected for every captured probe value.")
                add("- Keep Android enablement as `blocked` until write, readback, checksum/framing, and visible-state evidence agree.")
                add("")
                add("## Probe Matrix")
                add("")
                add("| Feature | Raw key | Android status | Probe values | Capture status |")
                add("| --- | --- | --- | --- | --- |")
                AirVisionFirmwareFeature.entries.forEach { feature ->
                    val target = targets.getValue(feature)
                    add(
                        "| ${feature.label.escapeTableCell()} | `${feature.rawValue}` | " +
                            "${feature.androidStatus.escapeTableCell()} | " +
                            "${feature.captureProbeValues.joinToString(" -> ").escapeTableCell()} | " +
                            "${target.summary.escapeTableCell()} |",
                    )
                }
                add("")
                add("## Per-Feature Capture Checklist")
                add("")
                AirVisionFirmwareFeature.entries.forEach { feature ->
                    val target = targets.getValue(feature)
                    add("### ${feature.label}")
                    add("")
                    syncItems[feature]?.let { item ->
                        add("- Desired value: ${item.desiredValue}")
                        add("- Android effect: ${item.androidEffect}")
                        add("- Hardware sync: ${item.hardwareSyncStatus}")
                        add("- Blocked reason: ${item.blockedReason}")
                    }
                    add("- Raw key: `${feature.rawValue}`")
                    add("- Probe values: ${feature.captureProbeValues.joinToString(" -> ")}")
                    add("- Capture ready: ${yesNo(target.captureReady)}")
                    add(
                        "- Writable report paths: ${
                            target.writeReportPathSummaries.ifEmpty { listOf("none") }.joinToString("; ")
                        }",
                    )
                    add(
                        "- Readable report paths: ${
                            target.readReportPathSummaries.ifEmpty { listOf("none") }.joinToString("; ")
                        }",
                    )
                    add("- Capture notes:")
                    add("  - Start a fresh USB capture.")
                    add("  - Change ${feature.label} through the probe values in order, pausing briefly after each value.")
                    add("  - Save the capture with the feature key and value sequence in the filename.")
                    add("  - Record any matching writable HID report path from the Android diagnostics export.")
                    add("")
                }
                add("## Capture Result Template")
                add("")
                add(
                    "| Feature | Write report ID | Write payload bytes | Readback report ID | Readback payload bytes | " +
                        "Checksum/framing notes | ASUS UI + M1 visible confirmation | Android enablement decision |",
                )
                add("| --- | --- | --- | --- | --- | --- | --- | --- |")
                AirVisionFirmwareFeature.entries.forEach { feature ->
                    add("| ${feature.label.escapeTableCell()} | pending | pending | pending | pending | pending | pending | blocked |")
                }
                add("")
                add("## Generated Metadata")
                add("")
                add("- Feature count: ${AirVisionFirmwareFeature.entries.size}")
            }
        return lines.joinToString("\n") + "\n"
    }

    private fun yesNo(value: Boolean): String = if (value) "yes" else "no"

    private fun String.escapeTableCell(): String = replace("|", "\\|")
}
