package ai.openclaw.app

object AirVisionWindowsProfileHandoffs {
    fun renderMarkdown(
        profileBackup: AirVisionProfileBackup,
        usbState: AirVisionUsbState,
    ): String {
        val activeProfile =
            profileBackup.profiles.firstOrNull { it.viewMode == profileBackup.activeViewMode }
                ?: profileBackup.profiles.firstOrNull()
        val info = usbState.deviceInfo
        val lines =
            buildList {
                add("# AirVision M1 Windows App Profile Handoff")
                add("")
                add(
                    "Generated by OpenClaw HUD for applying Android AirVision profile values in the " +
                        "ASUS AirVision Windows app.",
                )
                add(
                    "Use this when the M1 needs to stay connected to the Fold, or when the Windows/Cyber " +
                        "machine is used later for ASUS-only controls.",
                )
                add("")
                add("## Active Android Profile")
                add("")
                if (activeProfile != null) {
                    addProfile(activeProfile, profileBackup.customLabels, includeHeading = false)
                } else {
                    add("- No AirVision profile values were available.")
                }
                add("")
                add("## Active Android Runtime")
                add("")
                if (activeProfile != null) {
                    addRuntime(activeProfile, profileBackup)
                } else {
                    add("- Runtime profile unavailable because no active profile values were available.")
                }
                add("")
                add("## Windows App Apply Matrix")
                add("")
                if (activeProfile != null) {
                    addWindowsApplyMatrix(activeProfile, profileBackup)
                } else {
                    add("- Apply matrix unavailable because no active profile values were available.")
                }
                add("")
                add("## Installed Windows App Evidence")
                add("")
                addWindowsAppEvidence()
                add("")
                add("## All Saved Android Profiles")
                add("")
                profileBackup.profiles.sortedBy { AirVisionViewMode.fromRawValue(it.viewMode).ordinal }.forEach { profile ->
                    addProfile(profile, profileBackup.customLabels, includeHeading = true)
                    add("")
                }
                add("## Android HUD Controls")
                add("")
                addControls(profileBackup.hudControls)
                add("")
                add("## M1 Hardware Key Mapping")
                add("")
                addHardwareKeyMapping(profileBackup.hudControls)
                add("")
                add("## Windows Gesture Catalog")
                add("")
                addWindowsGestureCatalog(profileBackup.hudControls)
                add("")
                add("## Shortcut Menu Parity")
                add("")
                addShortcutMenu(profileBackup.hudControls, profileBackup.appPreferences)
                add("")
                add("## Windows-Only Spatial & Mirror Controls")
                add("")
                addWindowsOnlyControls(profileBackup.hudControls)
                add("")
                add("## Android Companion Parity States")
                add("")
                addCompanionParity(profileBackup.hudControls, profileBackup.appPreferences)
                add("")
                add("## Android App Preferences")
                add("")
                addPreferences(profileBackup.appPreferences)
                add("")
                add("## Caption and Translation Mode")
                add("")
                addCaptionMode(profileBackup.appPreferences)
                add("")
                add("## Support, Legal, and Registration")
                add("")
                addSupportMetadata()
                add("")
                add("## Windows/Cyber Apply Checklist")
                add("")
                add("- Open the ASUS AirVision Windows app on Cyber or another Windows host.")
                add(
                    "- Use the active-profile values above as the target View Mode, brightness, distance, " +
                        "IPD, Splendid, Eye Care, Motion Sync, Light Load Mode, and 3D Mode settings.",
                )
                add(
                    "- If Light Load Mode is on, keep IPD and 3D changes locked until Light Load Mode is " +
                        "off, matching the Android HUD guard.",
                )
                add(
                    "- Use Android HUD scale, placement, safe area, and physical-main-screen values only " +
                        "for OpenClaw HUD layout; they are not ASUS firmware settings.",
                )
                add(
                    "- Review the Windows-only spatial and mirror section before expecting Cursor Follow, " +
                        "Center Cursor, 3DoF, or Unity mirror behavior on Android.",
                )
                add("- Review Android companion parity states before treating M1-optional or firmware-gated features as live hardware support.")
                add(
                    "- After changing ASUS Windows app settings, reconnect the M1 to Android and export " +
                        "diagnostics or profile backup again.",
                )
                add("")
                add("## Android-Visible USB Context")
                add("")
                add("- Connected: ${yesNo(usbState.connected)}")
                add("- USB permission granted: ${yesNo(usbState.permissionGranted)}")
                add("- Device: ${displayValue(usbState.deviceLabel, "not detected")}")
                add("- USB ID: ${displayValue(usbState.vendorProduct ?: info.vendorProduct, "not detected")}")
                add("- Manufacturer: ${displayValue(info.manufacturerName, "not captured")}")
                add("- Product: ${displayValue(info.productName, "not captured")}")
                add("- Interface count: ${info.interfaceCount?.toString() ?: "not captured"}")
                add("- Serial status: ${serialStatus(info)}")
                add(
                    "- Android-visible firmware/version context: " +
                        displayValue(info.firmwareVersion, "pending ASUS HID protocol"),
                )
                add("- Firmware report paths: ${usbState.firmwareCapabilities.summary}")
                add("")
                add("## Android Boundary")
                add("")
                add(
                    "- Android stores these profile values and applies HUD-only effects such as software " +
                        "brightness, virtual distance scaling, HUD scale, placement, and Eye Care overlay.",
                )
                add("- Android does not send ASUS vendor reports until the HID protocol is captured, validated, and live-tested.")
                add(
                    "- Firmware updates, true panel preset writes, Windows mirror windows, virtual cursor, " +
                        "and 3DoF controls remain ASUS Windows app workflows.",
                )
                add(
                    "- This handoff intentionally omits raw USB serial numbers, raw USB captures, auth tokens, " +
                        "gateway endpoints, and chat history.",
                )
                add("")
                add("## ASUS Links")
                add("")
                add("- FAQ and tutorials: ${AirVisionSupportMetadata.default.faqUrl}")
                add("- AirVision M1 support: ${AirVisionSupportMetadata.default.supportUrl}")
            }
        return lines.joinToString("\n") + "\n"
    }

    private fun MutableList<String>.addWindowsApplyMatrix(
        profile: AirVisionBackupDisplayProfile,
        profileBackup: AirVisionProfileBackup,
    ) {
        AirVisionDiagnosticsSnapshots
            .windowsApplyMatrix(
                profile = profile,
                labels = profileBackup.customLabels,
                controls = profileBackup.hudControls.toRuntimeControls(),
                displayTarget = AirVisionHudDisplayTarget.fromRawValue(profileBackup.appPreferences.hudDisplayTarget),
            ).items
            .forEach { item ->
                add(
                    "- ${item.feature}: Windows app target ${item.windowsAppTarget}; Android effect ${item.androidEffect}; " +
                        "live M1 proof required: ${handoffLiveM1Proof(item)}; firmware gate: ${handoffFirmwareGate(item)}.",
                )
                add("  - Windows surface: ${item.windowsSurface}")
                add("  - Observed keys: ${item.observedSettingKeys.joinToString().ifBlank { "none" }}")
                add("  - Observed default: ${item.observedDefault}")
                add("  - Capture implication: ${item.captureImplication}")
            }
    }

    private fun MutableList<String>.addWindowsAppEvidence() {
        val evidence = AirVisionWindowsAppEvidence.diagnostics
        add("- App: ${evidence.appName} ${evidence.observedVersion}")
        add("- Build time: ${evidence.observedBuildTime}")
        add("- SDK: ${evidence.observedSdkVersion}")
        add("- HID library: ${evidence.observedHidLibrary}")
        add("- Settings data version: ${evidence.settingsDataVersion}")
        add("- Source: ${evidence.sourceSummary}")
        add("- Boundary: ${evidence.privacyBoundary}")
        evidence.settingMappings.forEach { mapping ->
            val keys =
                if (mapping.observedSettingKeys.isEmpty()) {
                    "none"
                } else {
                    mapping.observedSettingKeys.joinToString(", ")
                }
            add(
                "- ${mapping.feature}: ${mapping.windowsSurface}; keys: $keys; " +
                    "observed default: ${mapping.observedDefault}; Android mapping: ${mapping.androidMapping}; " +
                    "capture: ${mapping.captureImplication}",
            )
        }
    }

    private fun MutableList<String>.addProfile(
        profile: AirVisionBackupDisplayProfile,
        labels: AirVisionBackupCustomLabels,
        includeHeading: Boolean,
    ) {
        val mode = AirVisionViewMode.fromRawValue(profile.viewMode)
        val displayLabel = profileDisplayLabel(mode, labels)
        if (includeHeading) add("### $displayLabel")
        add("- View Mode: ${mode.label}")
        add("- Brightness: ${profile.brightnessPercent}%")
        add("- Screen distance: ${profile.distanceCm} cm")
        add("- IPD: ${ipdValue(profile)}")
        add("- Splendid: ${AirVisionSplendidMode.fromRawValue(profile.splendidMode).label}")
        add("- Blue Light Filter: ${blueLightFilterValue(profile)}")
        add("- Motion Sync: ${onOff(profile.motionSyncEnabled)}")
        add("- Light Load Mode: ${onOff(profile.lightLoadModeEnabled)}")
        add("- 3D Mode: ${threeDValue(profile)}")
        add("- Android HUD scale: ${profile.hudScalePercent}%")
        add("- Android HUD placement: ${AirVisionHudPlacement.fromRawValue(profile.hudPlacement).label}")
        add("- Android safe area: ${profile.safeAreaPercent}%")
        add("- Android physical main screen visible: ${yesNo(profile.physicalMainScreenVisible)}")
        addRuntimeSummary(profile)
    }

    private fun MutableList<String>.addRuntime(
        profile: AirVisionBackupDisplayProfile,
        profileBackup: AirVisionProfileBackup,
    ) {
        val runtime = runtimeProfileForProfile(profile)
        val importedRuntime =
            profileBackup.runtimeProfiles.firstOrNull {
                it.viewMode.trim().lowercase() == profile.viewMode.trim().lowercase()
            }
        add("- Effective HUD scale: ${runtime.effectiveHudScalePercent}%")
        add("- Transcript entries: ${runtime.hudTranscriptEntryCount}")
        add("- Caption entries: ${runtime.hudCaptionEntryCount}")
        add("- IPD adjustment available: ${yesNo(runtime.ipdAdjustmentEnabled)}")
        add("- 3D Mode available: ${yesNo(runtime.threeDModeAvailable)}")
        add("- Eye Care filter available: ${yesNo(runtime.blueLightFilterAvailable)}")
        add("- Color preview overlays: ${onOff(runtime.colorPreviewOverlaysEnabled)}")
        add("- Brightness dimming: ${onOff(runtime.brightnessDimmingEnabled)}")
        add(
            "- Embedded runtime metadata: " +
                when {
                    profileBackup.runtimeProfiles.isEmpty() -> "missing; recalculated from active profile values"
                    importedRuntime == null -> "missing for active profile; recalculated from active profile values"
                    runtimeMatches(importedRuntime, runtime) -> "current"
                    else -> "stale; recalculated from active profile values"
                },
        )
    }

    private fun MutableList<String>.addRuntimeSummary(profile: AirVisionBackupDisplayProfile) {
        val runtime = runtimeProfileForProfile(profile)
        add(
            "- Android runtime summary: effective HUD scale ${runtime.effectiveHudScalePercent}%, " +
                "transcript ${runtime.hudTranscriptEntryCount}, captions ${runtime.hudCaptionEntryCount}, " +
                "overlays ${onOff(runtime.colorPreviewOverlaysEnabled)}, dimming ${onOff(runtime.brightnessDimmingEnabled)}",
        )
        add(
            "- Android runtime controls: IPD ${availableUnavailable(runtime.ipdAdjustmentEnabled)}, " +
                "3D ${availableUnavailable(runtime.threeDModeAvailable)}, " +
                "Eye Care ${availableUnavailable(runtime.blueLightFilterAvailable)}",
        )
    }

    private fun MutableList<String>.addControls(controls: AirVisionBackupHudControls) {
        add("- Single tap: ${AirVisionHudTouchAction.fromRawValue(controls.singleTapAction).label}")
        add("- Double tap: ${AirVisionHudDoubleTapAction.fromRawValue(controls.doubleTapAction).label}")
        add("- Swipe: ${AirVisionHudSwipeAction.fromRawValue(controls.swipeAction).label}")
        add("- Brightness key: ${AirVisionHudKeyAction.fromRawValue(controls.brightnessKeyAction).label}")
        add("- Media key: ${AirVisionHudMediaKeyAction.fromRawValue(controls.mediaKeyAction).label}")
    }

    private fun MutableList<String>.addHardwareKeyMapping(controls: AirVisionBackupHudControls) {
        val brightnessKeyAction = AirVisionHudKeyAction.fromRawValue(controls.brightnessKeyAction)
        val mediaKeyAction = AirVisionHudMediaKeyAction.fromRawValue(controls.mediaKeyAction)
        add("- Brightness key action: ${brightnessKeyAction.label}")
        add("- Brightness key consumed by Android: ${yesNo(brightnessKeyAction != AirVisionHudKeyAction.None)}")
        add(
            "- Brightness key effect: " +
                when (brightnessKeyAction) {
                    AirVisionHudKeyAction.None -> "firmware or Android system handles brightness keys"
                    AirVisionHudKeyAction.ScrollChat -> "scrolls the HUD chat transcript by 160 px per press"
                    AirVisionHudKeyAction.AdjustBrightness -> "steps Android HUD dimming by 5% per press"
                    AirVisionHudKeyAction.AdjustDistance -> "steps virtual projection distance by 5 cm per press"
                },
        )
        add("- Media key action: ${mediaKeyAction.label}")
        add(
            "- Media key double-tap window: " +
                if (mediaKeyAction == AirVisionHudMediaKeyAction.DoubleTapToggleMic) {
                    "500 ms"
                } else {
                    "off"
                },
        )
        add(
            "- Firmware brightness passthrough expected: " +
                yesNo(brightnessKeyAction == AirVisionHudKeyAction.None),
        )
    }

    private fun MutableList<String>.addWindowsGestureCatalog(controls: AirVisionBackupHudControls) {
        val brightnessKeyAction = AirVisionHudKeyAction.fromRawValue(controls.brightnessKeyAction)
        val mediaKeyAction = AirVisionHudMediaKeyAction.fromRawValue(controls.mediaKeyAction)
        val doubleTapAction = AirVisionHudDoubleTapAction.fromRawValue(controls.doubleTapAction)
        add("- One-finger swipe forward/backward: ASUS quick brightness; Android mapping ${brightnessKeyAction.label}.")
        add("- One-finger tap: ASUS play/pause in floating mode; Android media/tap mapping ${mediaKeyAction.label}.")
        add("- Two-finger tap: ASUS instant transparent / lowest brightness; Android status firmware passthrough.")
        add("- One-finger tap in positioning mode: ASUS center virtual screens; Android status Windows-only virtual-screen action.")
        add("- One-finger double tap: ASUS positioning/floating switch; Android HUD double tap ${doubleTapAction.label}.")
        add("- Two-finger press and hold 1.5 seconds: ASUS 3D toggle; Android stores 3D preference and keeps panel write firmware-gated.")
        add("- One-finger press and hold 1.5 seconds, then slide: ASUS shortcut menu for brightness, volume, and distance; Android maps brightness/distance through HUD controls and speaker routing through AirVision preferences.")
    }

    private fun MutableList<String>.addShortcutMenu(
        controls: AirVisionBackupHudControls,
        preferences: AirVisionBackupAppPreferences,
    ) {
        val status = AirVisionShortcutMenuStatus.from(controls, preferences)
        add("- ${status.summary}")
        add("- Brightness: ${status.brightness}")
        add("- Volume: ${status.volume}")
        add("- Distance: ${status.distance}")
        add("- Android-mapped controls: ${status.androidMappedCount}")
        add("- Firmware/system-owned controls: ${status.firmwareOrSystemOwnedCount}")
    }

    private fun MutableList<String>.addWindowsOnlyControls(controls: AirVisionBackupHudControls) {
        val fallback = AirVisionSpatialMirrorFallback.from(controls)
        add("- Cursor Follow: Windows AirVision app only")
        add("- Center Cursor: Windows AirVision app only")
        add("- 3DoF: Windows laptop/AirVision app only")
        add("- Unity mirror window / Ctrl+Alt+E: Windows AirVision app only")
        add(
            "- Android distance hotkey fallback: " +
                if (fallback.distanceHotkeyMapped) "mapped to M1 brightness keys" else "off",
        )
        add("- Android mirror fallback: ${fallback.androidMirrorFallback}")
        fallback.androidMirrorFallbackActions.forEach { action ->
            add("- Fallback action: $action")
        }
        fallback.androidMirrorFallbackLaunchActions.forEach { action ->
            add("- Launch action ${action.label}: ${action.androidIntentAction}${action.fallbackIntentAction?.let { " (fallback $it)" } ?: ""}")
            add("  - ${action.summary}")
        }
        add("- M1 touch hardware passthrough: ${yesNo(fallback.hardwareTouchpadPassthrough)}")
        fallback.limitations.forEach { limitation ->
            add("- Limitation: $limitation")
        }
    }

    private fun MutableList<String>.addCompanionParity(
        controls: AirVisionBackupHudControls,
        preferences: AirVisionBackupAppPreferences,
    ) {
        val parity = AirVisionCompanionParity.fromBackup(controls, preferences)
        add("- ${parity.summary}")
        parity.entries.forEach { entry ->
            add("- ${entry.feature}: ${entry.androidState}; ${entry.evidence}")
        }
    }

    private fun MutableList<String>.addPreferences(preferences: AirVisionBackupAppPreferences) {
        val sourceLanguage =
            TranslationCaptionMode.languageFor(
                TranslationCaptionMode.normalizeLanguageCode(
                    preferences.translationCaptionSourceLanguage,
                    TranslationCaptionMode.DEFAULT_SOURCE_LANGUAGE,
                ),
            )
        val targetLanguage =
            TranslationCaptionMode.languageFor(
                TranslationCaptionMode.normalizeLanguageCode(
                    preferences.translationCaptionTargetLanguage,
                    TranslationCaptionMode.DEFAULT_TARGET_LANGUAGE,
                ),
            )
        add("- Startup view: ${AirVisionStartupDestination.fromRawValue(preferences.startupDestination).label}")
        add("- HUD display target: ${AirVisionHudDisplayTarget.fromRawValue(preferences.hudDisplayTarget).label}")
        add("- Companion language: ${AirVisionAppLanguage.fromRawValue(preferences.language).label}")
        add("- Speaker output: ${onOff(preferences.speakerEnabled)}")
        add("- Samsung/native captions: ${onOff(preferences.nativeCaptionsEnabled)}")
        add("- Translation captions: ${sourceLanguage.label} -> ${targetLanguage.label}")
        add("- Demo Mode: ${onOff(preferences.demoModeEnabled)}")
    }

    private fun MutableList<String>.addCaptionMode(preferences: AirVisionBackupAppPreferences) {
        val status = AirVisionCaptionModeStatus.from(preferences)
        add("- ${status.summary}")
        add("- Native provider: ${status.nativeProvider}")
        add("- Native captions enabled: ${onOff(status.nativeCaptionsEnabled)}")
        add("- OpenClaw fallback available: ${yesNo(status.openClawFallbackAvailable)}")
        add("- OpenClaw fallback model: ${status.openClawFallbackModel}")
        add("- OpenClaw fallback thinking: ${status.openClawFallbackThinking}")
        add("- Source language: ${status.sourceLanguageLabel} (${status.sourceLanguage})")
        add("- Target language: ${status.targetLanguageLabel} (${status.targetLanguage})")
        add("- Speaker labels: ${status.speakerLabels.joinToString()}")
    }

    private fun MutableList<String>.addSupportMetadata() {
        val metadata = AirVisionSupportMetadata.default
        add("- ${metadata.summary}")
        add("- EULA status: ${metadata.eulaStatus}")
        add("- Legal note: ${metadata.legalNote}")
        add("- Privacy boundary: ${metadata.privacyBoundary}")
        add("- FAQ and tutorials: ${metadata.faqUrl}")
        add("- Product registration: ${metadata.productRegistrationUrl}")
        add("- AirVision M1 support: ${metadata.supportUrl}")
    }

    private fun profileDisplayLabel(
        mode: AirVisionViewMode,
        labels: AirVisionBackupCustomLabels,
    ): String =
        when (mode) {
            AirVisionViewMode.Custom1 -> labels.custom1
            AirVisionViewMode.Custom2 -> labels.custom2
            else -> mode.label
        }

    private fun runtimeProfileForProfile(profile: AirVisionBackupDisplayProfile): AirVisionBackupRuntimeProfile =
        AirVisionProfileBackups.runtimeProfileFromSettings(AirVisionProfileBackups.settingsFromProfile(profile))

    private fun runtimeMatches(
        imported: AirVisionBackupRuntimeProfile,
        derived: AirVisionBackupRuntimeProfile,
    ): Boolean =
        imported.viewMode == derived.viewMode &&
            imported.ipdAdjustmentEnabled == derived.ipdAdjustmentEnabled &&
            imported.threeDModeAvailable == derived.threeDModeAvailable &&
            imported.blueLightFilterAvailable == derived.blueLightFilterAvailable &&
            imported.hudTranscriptEntryCount == derived.hudTranscriptEntryCount &&
            imported.hudCaptionEntryCount == derived.hudCaptionEntryCount &&
            imported.effectiveHudScalePercent == derived.effectiveHudScalePercent &&
            imported.colorPreviewOverlaysEnabled == derived.colorPreviewOverlaysEnabled &&
            imported.brightnessDimmingEnabled == derived.brightnessDimmingEnabled

    private fun blueLightFilterValue(profile: AirVisionBackupDisplayProfile): String =
        if (AirVisionSplendidMode.fromRawValue(profile.splendidMode) == AirVisionSplendidMode.EyeCare) {
            "${profile.blueLightFilterPercent}%"
        } else {
            "off (requires Eye Care)"
        }

    private fun ipdValue(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "${profile.ipdMm} mm (locked by Light Load Mode)"
        } else {
            "${profile.ipdMm} mm"
        }

    private fun threeDValue(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "off (locked by Light Load Mode)"
        } else {
            onOff(profile.threeDModeEnabled)
        }

    private fun lightLoadAndroidEffect(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "trimmed transcript/caption history and locked IPD/3D controls"
        } else {
            "full HUD history and unlocked IPD/3D controls"
        }

    private fun threeDAndroidEffect(profile: AirVisionBackupDisplayProfile): String =
        if (profile.lightLoadModeEnabled) {
            "locked off by Light Load Mode"
        } else {
            "stored desired state only"
        }

    private fun displayValue(
        value: String?,
        fallback: String,
    ): String = value?.takeIf { it.isNotBlank() } ?: fallback

    private fun serialStatus(info: AirVisionUsbDeviceInfo): String =
        info.serialStatus?.takeIf { it.isNotBlank() }
            ?: info.serialNumber?.takeIf { it.isNotBlank() }?.let { "available" }
            ?: "not captured"

    private fun handoffLiveM1Proof(item: AirVisionDiagnosticsWindowsApplyMatrixItem): String =
        when (item.feature) {
            "Display routing" -> "yes for DeX/M1 topology"
            "Gesture and hotkey settings" -> "yes for firmware-delivered events"
            "Windows spatial/mirror features" -> "Windows host"
            else -> yesNo(item.liveM1ProofRequired)
        }

    private fun handoffFirmwareGate(item: AirVisionDiagnosticsWindowsApplyMatrixItem): String =
        if (item.firmwareGate == "none") "no" else item.firmwareGate

    private fun AirVisionBackupHudControls.toRuntimeControls(): AirVisionHudControls =
        AirVisionHudControls(
            singleTapAction = AirVisionHudTouchAction.fromRawValue(singleTapAction),
            doubleTapAction = AirVisionHudDoubleTapAction.fromRawValue(doubleTapAction),
            swipeAction = AirVisionHudSwipeAction.fromRawValue(swipeAction),
            brightnessKeyAction = AirVisionHudKeyAction.fromRawValue(brightnessKeyAction),
            mediaKeyAction = AirVisionHudMediaKeyAction.fromRawValue(mediaKeyAction),
        )

    private fun onOff(value: Boolean): String = if (value) "on" else "off"

    private fun yesNo(value: Boolean): String = if (value) "yes" else "no"

    private fun availableUnavailable(value: Boolean): String = if (value) "available" else "unavailable"
}
